format = "default"
severity = "warning"
error_code = 1
warning_code = 0
comment = "This is a configuration file for flint, the filesystem linter. More information here: https://github.com/z0mbie42/flint"
ignore_files = ["**/.*", "**/.*/**/.*", "**/.*/**/*", "README.md", "LICENSE", "Gopkg.{toml,lock}"]
ignore_directories = ["**/.*", ".**/*"]

[rules]
  [rules.no_dir_dot]
  [rules.no_empty_name]
  [rules.no_leading_underscores]
  [rules.no_multi_extensions]
  [rules.no_trailing_underscores]
  [rules.no_whitespaces]
  [rules.snake_case]
