comment = "This is a configuration file for flint, the filesystem linter. More information here: https://github.com/z0mbie42/flint"
format = "default"
severity = "warning"
error_code = 1
warning_code = 0
match_format = "blob"
ignore_files = [".*", "vendor", "LICENSE", "README.md", "Gopkg.*"]
ignore_directories = [".*", "vendor"]

[rules]
  [rules."dir/no_dot"]
  [rules."file/lower_case_ext"]
  [rules."file/no_multi_ext"]
  [rules.no_empty_name]
  [rules.no_leading_underscores]
  [rules.no_trailing_underscores]
  [rules.no_whitespaces]
  [rules.snake_case]
    severity = "error"
