comment = "This is a configuration file for flint, the filesystem linter. More information here: https://github.com/z0mbie42/flint"
format = "default"
severity = "warning"
error_code = 1
warning_code = 0
ignore_files = ["(^|/)\\..*", "^Gopkg\\.(toml|lock)$", "^(LICENSE|README\\.md)$"]
ignore_directories = ["(^|/)\\..*"]

[rules]
  [rules."dir/no_dot"]
  [rules."file/lower_case_extension"]
  [rules.no_empty_name]
  [rules.no_leading_underscores]
  [rules.no_multi_extensions]
  [rules.no_trailing_underscores]
  [rules.no_whitespaces]
  [rules.snake_case]
