# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

go:
  - 1.10.3

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - make test
  - make
