name: flint
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Fast and configurable filesystem (file and directory names) linter 
description: |
  You think there is no place in code reviews to discuss about files naming conventions ? Impose consistent files and directories naming rules with flint: the filesystem linter.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  flint:
    source: .
    plugin: go
    go-importpath: github.com/z0mbie42/flint

apps:
  flint:
    command: flint
